# Generated by Django 4.2.15 on 2024-08-12 05:13

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_kyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to=account.models.user_directory_path
            ),
        ),
    ]
