# Generated by Django 4.2.15 on 2024-08-14 09:03

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=models.CharField(
                default=account.utils.create_new_ref_number,
                editable=False,
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                default=account.utils.create_new_ref_number,
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="pin_number",
            field=models.CharField(max_length=4),
        ),
    ]
